### ISSUE TITLE
Players crash upon joining party

### ISSUE THREAD

**Issue by kurisubrooks** [kharidiron/StarryPy#24]
After about 5-10 seconds after joining a party, the person receiving the invitation will crash.

**Comment by kurisubrooks** [comment]
Occasionally, doesn't happen 100% of the time.

**Comment by kharidiron** [comment]
Haven't been able to reproduce. Will test more.

**Comment by kharidiron** [comment]
I'm calling this done. It was most likely due to the unstable state of the wrapper at the time.

**Comment by kurisubrooks** [comment]
Yup, hasn't happened lately. At all. Good job Kharidiron :)
