### ISSUE TITLE
Server randomly kicking players, but user remains

### ISSUE THREAD

**Issue by kurisubrooks** [kharidiron/StarryPy#25]
The server will occasionally say "$username has left."
When they're still logged in, making them no longer accessible through the wrapper.

**Comment by kurisubrooks** [comment]
![](http://kurisubrooks.com/img/2015-01-31_2338.png)

**Comment by kharidiron** [comment]
I think this was due to some bugs from before, but will need to test more.

**Comment by kharidiron** [comment]
This is also likely due to the unstable state of the wrapper at the time, as I have not had this happen since its initial report.

**Comment by kurisubrooks** [comment]
Yup, seems good now. Thanks ^o^
