### ISSUE TITLE
Players unknowingly bypassing server wrapper

### ISSUE THREAD

**Issue by kurisubrooks** [kharidiron/StarryPy#26]
New players with legit clients, and normal usernames are still somehow bypassing the wrapper.

**Comment by kharidiron** [comment]
I think this might be due to people, at the time, connecting using the IP address, and not the DNS name. As this isn't an issue with StarryPy itself, I'm going to close this issue.

**Comment by kurisubrooks** [comment]
Yup that's why @kharidiron. One of the users said it's due to this: (http://starbound-servers.net/server/1151/)[http://starbound-servers.net/server/1151/] not being updated.
