### ISSUE TITLE
Fix connect_response packet

### ISSUE THREAD

**Issue by Zwergengraf** [kharidiron/StarryPy#42]
reject_with_reason in plugins/core/player_manager/plugin.py is broken, clients with "bad" character names are not rejected - they are online but bypass the wrapper (do not appear in the list of players and so on). Bad stuff.

Possible fix: https://gist.github.com/Zwergengraf/bbaeb39ac5af27bdcbb4

**Comment by kharidiron** [comment]
KK, thanks for the help. I applied your patch, and it looks like it definitely works for names like '     ' (all spaces). I haven't been able to get accented names to work, since starbound keeps rejecting them before I can log in. May need to borrow someone international to test.
